### ISSUE TITLE
biomass() and standStruct() fail when using multi-state, remote FIADB object with specific evalids

### ISSUE THREAD

**Issue by jamisbruening** [hunter-stanke/rFIA#18]
I'm having some issues when running biomass() and standStruct() on a multi-state FIADB that is not loaded into memory, when also passing specific EVALIDS to clipFIA().  This test is using Alabama, and while its happened for several other states as well, I have not exhaustively tested every state.

From what I can tell this problem only occurs with the combination of 1) a multi-state FIADB (tested for 2 states and entire CONUS) 2) that FIADB not being loaded in memory, (using inMemory=F), and 3) passing specific EVALIDS to clipFIA() to enable estimates not using the most recent inventories.

When things break, this is the error message I get:

```
Error in `$<-.data.frame`(`*tmp*`, "prev", value = 0) : 
  replacement has 1 row, data has 0
```

Code used to produce said error:

```
rm(list=ls())

# devtools::install_github('hunter-stanke/rFIA')
library(rFIA)

# evalids for Alabama total volume and area: 2000 - 2012
ee <- c(10501, 11101, 10601, 10901, 10801, 11001, 10001, 10301, 10401, 10101, 11201, 10701, 10201)

# works
FIADB <- readFIA('/Volumes/RESEARCH/rFIA/original_data', inMemory=F, nCores=6, states='AL')
fiadb <- clipFIA(FIADB, mostRecent = T, nCores=6)
bio <- biomass(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)
stst <- standStruct(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)

# works
FIADB <- readFIA('/Volumes/RESEARCH/rFIA/original_data', inMemory=T, nCores=6, states='AL')
fiadb <- clipFIA(FIADB, mostRecent = T, nCores=6)
bio <- biomass(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)
stst <- standStruct(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)

# works
FIADB <- readFIA('/Volumes/RESEARCH/rFIA/original_data', inMemory=T, nCores=6, states=c('AL','GA'))
fiadb <- clipFIA(FIADB, mostRecent = T, nCores=6)
bio <- biomass(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)
stst <- standStruct(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)

# works
FIADB <- readFIA('/Volumes/RESEARCH/rFIA/original_data', inMemory=F, nCores=6)
fiadb <- clipFIA(FIADB, mostRecent = T, nCores=6)
bio <- biomass(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)
stst <- standStruct(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)

# works
FIADB <- readFIA('/Volumes/RESEARCH/rFIA/original_data', inMemory=F, nCores=6, states=c('AL','GA'))
fiadb <- clipFIA(FIADB, mostRecent = T, nCores=6)
bio <- biomass(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)
stst <- standStruct(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)



# breaks
FIADB <- readFIA('/Volumes/RESEARCH/rFIA/original_data', inMemory=F, nCores=6)
fiadb <- clipFIA(FIADB, mostRecent = FALSE, evalid = ee, nCores=6)
bio <- biomass(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)
stst <- standStruct(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)

# breaks
FIADB <- readFIA('/Volumes/RESEARCH/rFIA/original_data', inMemory=F, nCores=6, states=c('AL','GA'))
fiadb <- clipFIA(FIADB, mostRecent = FALSE, evalid = ee, nCores=6)
bio <- biomass(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)
stst <- standStruct(fiadb, grpBy = COUNTYCD, totals = T, variance = F, nCores = 6)

```

Thank you!!

**Comment by hunter-stanke** [comment]
Sorry for the delayed reply, and thanks for sending this my way! I'll dig into it today, and hopefully have a fix up in the next few hours.

**Comment by hunter-stanke** [comment]
I've found the issue, and just pushed up a fix. 

The problem is that the list of EVALIDs `ee` pertains only to Alabama, i.e., none of those listed are affiliated with the Georgia inventory. When we're working with an in-memory database, this is fine, as we're simply asking clipFIA to drop all Georgia inventories and retain the selected Alabama inventories. However, rFIA's out-of-memory methods will read in states one at a time, evaluate the call to clipFIA, and then proceed with estimation. So when Georgia gets read in, we're asking it to drop all of it's inventories, leaving us with no data and hence resulting in a less than informative error message. 

For in-memory databases, I don't mind the current behavior (i.e., the ability to drop selected states entirely should you choose to). Thus I've have only added a warning for these cases - the message will simply tell you what states are missing from the list of EVALIDs.

For remote databases however, I don't see much benefit to allowing states to be dropped by clipFIA, as this could be accomplished more efficiently via the states argument with readFIA. Hence, an error will be thrown in these cases. The message will tell you what states are missing, and to either add EVALIDs for the missing states or drop these states from the call to readFIA. 

Could you re-install from GitHub and confirm that behavior on your end? I'm open to suggestions on clipFIA's behavior here too. If consistency between in-memory and out-of-memory approaches is more desirable, we can certainly go that route.
